sonar.projectKey=danieloliveira7_Receitas
sonar.organization=danieloliveira7

sonar.projectName=Receitas
sonar.sources=app,routes,config,database
sonar.tests=tests

sonar.php.tests.reportPath=junit.xml
sonar.sourceEncoding=UTF-8

sonar.exclusions=vendor/**,storage/**,bootstrap/cache/**,node_modules/**